name: flutter_datepickers
description: Loycon datepickers for Flutter.
version: 0.0.1
homepage: https://github.com/hanyska/flutter_datepickers

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ">=0.1.0<2.0.0"
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.janua.flutter_datepickers
        pluginClass: FlutterDatepickersPlugin
      ios:
        pluginClass: FlutterDatepickersPlugin